package web

import (
	"context"
	"net/http"
	"time"

	"github.com/google/uuid"
)

const requestIDHeader = "X-Request-ID"

type requestIDKey struct{}
type requestStartedAtKey struct{}

func requestIDFrom(r *http.Request) string {
	if id, ok := r.Context().Value(requestIDKey{}).(string); ok {
		return id
	}
	return ""
}

// requestStartedAtFrom returns the timestamp captured at the outer request-ID
// middleware, allowing usage, trace, and debug records to share one request
// start time even when inner middleware performs body capture or authentication.
func requestStartedAtFrom(r *http.Request) time.Time {
	if startedAt, ok := r.Context().Value(requestStartedAtKey{}).(time.Time); ok {
		return startedAt
	}
	return time.Now()
}

// requestID attaches a server-generated correlation identifier and the request
// start time to every request. The identifier is generated by the service rather
// than trusting a client-supplied value, so logs and support reports cannot be
// spoofed.
func requestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id := uuid.NewString()
		startedAt := time.Now()
		w.Header().Set(requestIDHeader, id)
		ctx := context.WithValue(r.Context(), requestIDKey{}, id)
		ctx = context.WithValue(ctx, requestStartedAtKey{}, startedAt)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
